### ISSUE TITLE
Occasional Error

### ISSUE THREAD

**Issue by MediciPrime** [rr1859/R.4Cker#11]
Hello Ramya,

I am occasionally encountering the following error while performing a nearBait (k=10), cis (k=10) or transAnalysis (k=20) after having successfully created `my_obj`:  

`Error in 2:nrow(windows) : argument of length 0
Calls: nearBaitAnalysis ... viterbi3State -> write.table -> is.data.frame -> merge_windows
Execution halted`

**Note**: this error is 'fixed' once the analysis is repeated

Would you happen to know the purpose of these errors?  

Thank you,
Behram

**Comment by nagoue** [comment]
Hi,

I also get the same error : In p0 * vscale[(neq + 2):(nc + np + 1)]: longer object length is not a multiple of shorter object length
except that it is not "fixed" when I rerun the analysis.
Could you get an explanation ? 
Cheers,
Nadia
