### ISSUE TITLE
warning messages in nearBaitAnalysis and cisAnalysis

### ISSUE THREAD

**Issue by nagoue** [rr1859/R.4Cker#14]
Hello Ramya,

I am stuck with the nearBaitAnalysis and cisAnalysis. I attached 2 toy datasets.
I processed the data as follow:
GFP     <- read.delim(file = "~/Documents/GFP.bedgraph", header = F, stringsAsFactors = F)
RNAi     <- read.delim(file = "~/Documents/RNAi.bedgraph", header = F, stringsAsFactors = F)

my_test = createR4CkerObjectFromDFs(dfs = c("GFP","RNAi"),
                                      bait_chr="X", bait_coord= 21630544,
                                      bait_name = "my_bait", primary_enz = "CATG",
                                      samples = c("GFP","RNAi"), conditions = c("GFP", "RNAi"),
                                      replicates = c(1,1), species = "dm",
                                      output_dir = "~/Documents/results/4C/bed/test")

nb_results_test    = nearBaitAnalysis(my_test, k = 3)

The output is:
[1] "Building adaptive windows..."
[1] "Normalizing counts..."
[1] "Generating synthetic samples...."
[1] "Parameter estimation....."
[1] "Warning: only 1 iteration. Using starting parameters"
[1] "Parameter estimation....."
[1] "Warning: only 1 iteration. Using starting parameters"
[1] "Parameter estimation....."
[1] "Warning: only 1 iteration. Using starting parameters"
[1] "Parameter estimation....."
[1] "Warning: only 1 iteration. Using starting parameters"
[1] "BED file of highest interacting domains for near the bait on the cis chromosome are saved in ~/Documents/results/4C/bed/test/"
Warning messages:
1: In p0 * vscale[(neq + 2):(nc + np + 1)] :
 longer object length is not a multiple of shorter object length 
2: In p0 * vscale[(neq + 2):(nc + np + 1)] :
 longer object length is not a multiple of shorter object length 
3: In p0 * vscale[(neq + 2):(nc + np + 1)] :
 longer object length is not a multiple of shorter object length 
4: In p0 * vscale[(neq + 2):(nc + np + 1)] :
 longer object length is not a multiple of shorter object length 

I got similar output with the command lines 
nb_results_test   = nearBaitAnalysis(my_test, k = 5)
cis_results_test   = cisAnalysis(my_test, k = 10)

Is there some parameter to set up in order to avoid  "Warning: only 1 iteration. Using starting parameters" ?
The second warning " In p0 * vscale[(neq + 2):(nc + np + 1)] : ..."  sounds more like an error. Do you have any idea from where this issue could come from and how to solve it ?

Many thanks in advance for your help,

[GFP.txt](https://github.com/rr1859/R.4Cker/files/566000/GFP.txt)
[RNAi.txt](https://github.com/rr1859/R.4Cker/files/566004/RNAi.txt)

**Comment by rr1859** [comment]
Its failing at the parameter estimation step. When you created the 4Cker object did you get a warning message about QC? It seems to me like your data is quiet sparse and the near (2MB around the bait)

**Comment by nagoue** [comment]
Hi Ramya,
I arrived to the same conclusion yesterday! There is no warning about the QC. But my guess is that it is due to the repetitive elements close to the viewpoint... I have to figure out how to handle those repeat sequences with the masked and unmasked genome. Thank you for your feedback. Nadia

**Comment by rr1859** [comment]
You should still have gotten normalized bedgraph files so you can visualize those. If the adaptive windows did not work well due to the large repeats and you are trying to detect differences between your conditions, try using DESeq2 with fixed windows starting from the raw bedgraph files.

**Comment by nagoue** [comment]
Thank you for your advice.

2016-11-08 18:13 GMT+01:00 Ramya Raviram <notifications@github.com>:
