### ISSUE TITLE
reduced_genome.sh output has restriction enzyme sites

### ISSUE THREAD

**Issue by iprada** [rr1859/R.4Cker#20]
Hi, after running reduced_genome.sh, the file  hg19_dpnii_flanking_sequences_40_unique.fa has the restriction site of the enzyme used "GATC", should that be posible?

**Comment by rr1859** [comment]
Hi sorry for the delayed response. Yes that can happen in instances where two RE sites are less than 40bp apart.

**Comment by iprada** [comment]
Don't worry! thanks!
