### ISSUE TITLE
What if I have only one replicate per condition, and is there any way to ignore the QC?

### ISSUE THREAD

**Issue by sameet** [rr1859/R.4Cker#38]
I have the following:

    '''
    enz.df <-  read.table("hg19_nlaiii_flanking_sites_76_unique_2.bed", stringsAsFactors = F)
    fl <- list.files("bait1A", pattern = "*und.bedGraph", full.names=T)
    my_obj <- createR4CkerObjectFromFiles(files = fl, 
                                                                         bait_chr = "chr12", 
                                                                         bait_coord=125313518, 
                                                                         bait_name="1A",
                                                                         replicates = 1,
                                                                         primary_enz = "CATG",
                                                                         samples = c("Re", "Ri"),
                                                                         conditions = c("Reference", "Risk"),
                                                                         species = "hs",
                                                                         output_dir = "./bait_1A_results"
                                                                          enz_file = enz.df)

    Error in createR4CkerObjectFromFiles(files = fl, bait_chr = "chr12", bait_coord = 125313518,  : rence" Number of samples does not matchdir = "bait1A_results", enz_file = enz.df)
    """

Is there anyway this calculation could be wrong.  When I do the following, I am pretty sure it should pass the QC.  More than 40% of the reads are within 1 kB of the bait location.  Any help will be greatly appreciated.

**Comment by rr1859** [comment]
Hi, 

You have to specify the number of replicates per sample. 

enz.df <-  read.table("hg19_nlaiii_flanking_sites_76_unique_2.bed", stringsAsFactors = F)
fl <- list.files("bait1A", pattern = "*und.bedGraph", full.names=T)
my_obj <- createR4CkerObjectFromFiles(files = fl, 
                                                                     bait_chr = "chr12", 
                                                                     bait_coord=125313518, 
                                                                     bait_name="1A",
                                                                     replicates = c(1,1)
                                                                     primary_enz = "CATG",
                                                                     samples = c("Re", "Ri"),
                                                                     conditions = c("Reference", "Risk"),
                                                                     species = "hs",
                                                                     output_dir = "./bait_1A_results"
                                                                      enz_file = enz.df)

**Comment by sameet** [comment]
Ah,

That is useful.  Thanks.

Sameet
