### ISSUE TITLE
Error in nearBaitAnalysis 

### ISSUE THREAD

**Issue by Anuragksingh** [rr1859/R.4Cker#50]
Hello,
When using the code line:

nb_results=nearBaitAnalysis(my_obj,k=5)

[1] "Building adaptive windows..."
Error in coord[i] - coord[(i - k)] : 
  non-numeric argument to binary operator

I am getting this error while doing near bait analysis. Kindly help me out with this.
Thanks

**Comment by Inswasti** [comment]
Hi,
I also got the same error. Have removed all non-numeric arguments from the bed files.
But still ended up with the same error, for all 3 analyses.
Does it matter if my coverage did not pass the QC and I just went ahead with analyses?
I got the error above even when running trans analysis.

Thanks
